version: '3.8'

services:
  omnipilot_db:
    image: ankane/pgvector:latest
    container_name: omnipilot_db
    restart: always
    environment:
      POSTGRES_USER: omnipilot
      POSTGRES_PASSWORD: omnipilot_pass
      POSTGRES_DB: omnipilot_db
    ports:
      - "5433:5432"
    volumes:
      - omnipilot_pgdata:/var/lib/postgresql/data

volumes:
  omnipilot_pgdata:
