from sqlalchemy import Column, Integer, String, DateTime, JSON, ForeignKey
from sqlalchemy.sql import func
from pgvector.sqlalchemy import Vector
from .config import Base

class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, index=True)
    username = Column(String, unique=True, index=True)
    email = Column(String, unique=True, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class Session(Base):
    __tablename__ = "sessions"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class AgentRun(Base):
    __tablename__ = "agent_runs"
    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(Integer, ForeignKey("sessions.id"))
    agent_type = Column(String)  # 'supervisor', 'browser', 'calendar', 'research'
    status = Column(String)      # 'running', 'completed', 'failed', 'interrupted'
    state = Column(JSON)         # To store LangGraph state
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    completed_at = Column(DateTime(timezone=True), nullable=True)

class Task(Base):
    __tablename__ = "tasks"
    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(Integer, ForeignKey("sessions.id"))
    description = Column(String)
    status = Column(String)      # 'pending', 'in_progress', 'completed', 'failed'
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class Approval(Base):
    __tablename__ = "approvals"
    id = Column(Integer, primary_key=True, index=True)
    agent_run_id = Column(Integer, ForeignKey("agent_runs.id"))
    action_type = Column(String) # e.g. 'execute_browser', 'execute_calendar'
    action_details = Column(JSON)
    status = Column(String)      # 'pending', 'approved', 'rejected'
    created_at = Column(DateTime(timezone=True), server_default=func.now())

# --- Phase 2 Memory & History Tables ---

class UserMemory(Base):
    __tablename__ = "user_memories"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    key = Column(String, index=True)                 # e.g. 'favorite_restaurant'
    value = Column(JSON, nullable=True)               # e.g. '{"name": "Luigi's"}'
    text_chunk = Column(String, nullable=True)        # Context for RAG queries
    embedding = Column(Vector(768), nullable=True)   # nomic-embed-text is 768-dim
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class MeetingHistory(Base):
    __tablename__ = "meeting_histories"
    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(Integer, ForeignKey("sessions.id"))
    title = Column(String)
    summary = Column(String)
    briefing = Column(String)                         # Markdown briefing generated by research agent
    embedding = Column(Vector(768), nullable=True)    # 768-dimensional pgvector
    created_at = Column(DateTime(timezone=True), server_default=func.now())
